# docker-compose.yml
version: "3.8"

services:
  expo-app:
    build: .
    ports:
      - "19000:19000" # Main Expo server
      - "19001:19001" # Development server
      - "19002:19002" # Dev tools
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=${REACT_NATIVE_PACKAGER_HOSTNAME:-localhost}
    command: npm start
